apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: wordpress
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQ=   # Base64 encoded 'password'
  mysql-database: d29yZHByZXNz       # Base64 encoded 'wordpress'
  mysql-user: dXNlcg==               # Base64 encoded 'user'
  mysql-password: cGFzc3dvcmQ=       # Base64 encoded 'password'
