apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: default
type: Opaque
data:
  wordpress-db-host: <base64-encoded-db-host>
  wordpress-db-user: <base64-encoded-db-user>
  wordpress-db-password: <base64-encoded-db-password>
  wordpress-db-name: <base64-encoded-db-name>